
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[426] =
    {   0,
        0,    0,    0,    0,    0,    0,   73,   71,   61,   61,
       54,   71,   58,   55,   54,   71,   53,   54,   54,   58,
       54,   53,   55,   44,   45,   56,   52,   55,   57,   55,
       56,   60,   60,   60,   71,   55,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   52,   55,   54,   58,    5,    5,    5,   69,
       70,   61,   55,    0,    0,    0,   58,    0,    0,    0,
        0,   59,   57,   59,    0,    0,   54,   53,    0,   47,
        1,    0,   47,   44,    0,    0,   44,   44,    0,   44,
       45,   45,   45,   45,   52,   55,   55,   60,    0,   60,

        0,   62,    0,    0,    0,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   35,   60,   60,   60,   60,   60,
       60,   39,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,    0,    0,    0,    5,    5,    3,    5,
       69,   51,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   50,    0,    0,    0,    0,   56,    0,   47,
        0,    6,    0,   48,   44,   44,   44,   44,    0,   46,
       45,   45,   45,   45,    0,    0,   60,    0,    0,    0,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   37,   60,   60,   18,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   63,    0,    0,    0,    0,    0,
        0,   47,   48,   44,    0,   46,   46,   46,   45,    0,
        0,   60,    0,    0,   60,   60,   60,   10,   60,   32,
       11,   60,   60,   60,   60,   36,   14,   60,   60,   38,
       60,   19,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   29,   60,   60,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   46,   46,   46,   46,    0,    0,   60,    0,

        0,    7,   60,   60,   31,   12,   60,   60,   60,   60,
       16,   60,   60,   60,   60,   22,   60,   60,   60,   60,
       60,   60,   27,   60,   60,   43,    0,    0,    0,    0,
        0,   64,    0,    0,   67,    0,    0,    0,   49,   46,
        0,    0,   60,   60,    0,   60,   60,   60,   60,   60,
       13,   15,   17,   60,   60,   40,   23,   41,   24,   25,
       42,   60,   60,   60,    0,    0,    0,    0,    0,   65,
        0,    0,   49,    0,   60,   60,    0,   60,   60,   60,
       34,   60,   60,   26,   60,   60,    0,    0,    0,   66,
        0,    0,   60,   60,    0,    8,   60,   33,   20,   21,

       28,   30,    0,    0,    0,    0,   60,   60,    0,   60,
        0,   68,    0,    0,    0,   60,   60,    9,   60,   60,
       60,   60,    2,    4,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   38,   39,   40,   41,
       35,   35,   35,   42,   43,   35,   35,   44,   35,   35,
       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   35,   59,   60,   61,   62,
       63,   64,   35,   65,   66,   67,   68,   69,   70,   71,
       72,   73,   74,   75,   76,   77,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[78] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    4,    1,    1,    1,    5,    1,    6,    6,
        7,    1,    1,    1,    1,    8,    9,    7,    7,    7,
        7,    7,    7,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   11,   11,    1,   11,    1,    1,   10,    6,
        6,    7,    7,    7,    6,   10,   10,   10,   10,   10,
       10,   11,   10,   10,   11,   10,   11,   11,   11,   10,
       11,   10,   10,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[490] =
    {   0,
        0, 1056,   65,   66,   74,   75, 1062, 1064,   80,   83,
     1036, 1014,   84,   67,   81, 1013, 1064, 1033,   80, 1064,
       82,   92,   97,  128,  109, 1031, 1064,  109, 1031,   70,
     1064, 1009,   70,   93,  100, 1029,  121,   68,   58,  116,
      107,  118,   72,  112,  128,  113,  138,  140,  109,   78,
      139,  147, 1064,  978, 1064,  199,  998, 1033,  133,    0,
     1064,  209, 1064,  148,  195,  187, 1064,  996,   65,  994,
      990, 1039, 1064, 1064,  190,  199, 1064, 1064, 1029,  241,
     1064, 1042,  256,  265,  214,  206,  180,  168, 1027,  211,
      286,  187,  172,  244, 1064, 1018, 1017,  995,  201,  203,

      994, 1064,    0,    0,  964,  218,  237,  204,  162,  226,
      248,  263,  253,  271,  252,  275,  276,  278,  284,  285,
      281,  992,  282,  289,  297,  292,  306,  310,  311,  312,
      315,  320,  313,  330,  363,  196,  983,  320, 1064,  982,
        0, 1064,  364,    0,    0,    0,  980,  968,  980, 1029,
      969, 1008, 1064,  367,    0,    0,    0, 1064,  375, 1064,
     1026, 1064,  271,  378,  325, 1064,  991,  967,    0,  375,
      357, 1064,  989,  965,    0,    0,  368,    0,    0,  999,
      339,  344,  357,  363,  374,  373,  376,  362,  384,  170,
      385,  386,  390,  396,  977,  391,  394,  976,  399,  402,

      403,  404,  410,  405,  407,  411,  412,  416,  417,  413,
      419,  420,  418,  428,  959,  968,  473,    0,  514,    0,
      961,  964,  959, 1013, 1064,  961,  471,    0,  560,    0,
      465,  476, 1064, 1064,  465,  457,  450,  455, 1064,    0,
        0,  462,    0,    0,  443,  458,  456,  968,  459,  967,
      966,  461,  453,  470,  480,  965,  964,  484,  481,  963,
      475,  962,  486,  493,  507,  495,  505,  508,  515,  504,
      511,  529,  532,  468,  795,  509,  531,  779,  577,    0,
        0,    0,  776,  833,  780,  828,  326,    0,    0,    0,
      533,  582,  541, 1064,  792,  768,    0,    0,  586,    0,

        0,  780,  540,  541,  779,  773,  558,  559,  571,  562,
      767,  572,  561,  575,  581,  758,  583,  584,  585,  588,
      589,  594,  752,  592,  595,  751,  718,    0,    0,  720,
      746, 1064,  745,  744, 1064,    0,    0,  630,  637, 1064,
        0,    0,  619,  606,    0,  700,  614,  601,  596,  615,
      699,  698,  696,  621,  620,  695,  694,  693,  689,  688,
      687,  616,  623,  627,  679,    0,  638,  728,  727, 1064,
        0,  666, 1064,    0,  640,  643,    0,  634,  635,  637,
      655,  642,  644,  549,  647,  648,  415,    0,  403, 1064,
        0,    0,  657,  662,    0,  355,  650,  293,  291,  210,

      110,   75,  712,    0,    0,    0,  667,  673,    0,  652,
      719, 1064,    0,    0,    0,  671,  692,   51,  680,  691,
      683,  704, 1064, 1064, 1064,  750,  761,  772,  783,  789,
      800,  811,  821,  831,  842,  849,  851,  853,  855,  857,
      859,  866,  872,  874,  876,  878,  880,  882,  884,  886,
      888,  890,  892,  894,  896,  898,  900,  902,  904,  906,
      913,  924,  930,  932,  934,  936,  938,  940,  942,  944,
      951,  957,  959,  961,  963,  965,  967,  974,  980,  982,
      984,  986,  988,  990,  992,  994,  996,  998, 1000
    } ;

static yyconst flex_int16_t yy_def[490] =
    {   0,
      425,    1,  426,  426,  427,  427,  425,  425,  425,  425,
      425,  428,  425,  425,  425,  429,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  430,  430,  430,  425,  425,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  425,  425,  425,  425,  431,  425,  431,  432,
      425,  425,  425,  428,  433,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  429,  434,  425,  425,  425,  425,
      425,  435,  425,  425,  425,  425,  425,  425,  436,  425,
      425,  425,  425,  425,  425,  425,  425,  430,  425,  430,

      428,  425,  437,  438,  425,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  425,  425,  425,  431,  431,  425,  431,
      432,  425,  428,  439,  440,  441,  425,  425,  425,  442,
      425,  425,  425,  429,  443,  444,  445,  425,  425,  425,
      435,  425,  425,  425,  425,  425,  425,  425,  446,  436,
      425,  425,  425,  425,  447,  448,  430,  449,  450,  425,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,

      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  425,  425,  428,  451,  428,  452,
      425,  425,  425,  442,  425,  425,  429,  453,  429,  454,
      425,  425,  425,  425,  446,  425,  425,  425,  425,  455,
      456,  430,  457,  458,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  425,  428,  459,
      219,  460,  425,  461,  425,  462,  429,  463,  229,  464,
      425,  425,  425,  425,  425,  425,  465,  466,  430,  467,

      468,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  425,  469,  470,  425,
      461,  425,  471,  462,  425,  472,  473,  425,  425,  425,
      474,  475,  430,  430,  476,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  425,  477,  428,  478,  471,  425,
      479,  429,  425,  480,  430,  430,  481,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  425,  482,  478,  425,
      483,  484,  430,  430,  485,  430,  430,  430,  430,  430,

      430,  430,  425,  486,  487,  488,  430,  430,  489,  430,
      425,  425,  470,  473,  475,  430,  430,  430,  430,  430,
      430,  430,  425,  425,    0,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425
    } ;

static yyconst flex_int16_t yy_nxt[1142] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   32,
       32,   32,   32,   32,   32,   32,   34,   32,   32,   32,
       32,   32,   32,   32,   17,   35,   17,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   32,   45,   32,   46,
       32,   32,   32,   32,   47,   48,   49,   50,   51,   52,
       32,   32,   32,   53,   54,   17,   55,   58,   58,   61,
       61,   62,   62,   62,   62,   62,   62,   66,   72,   63,
       67,   73,   74,   77,   63,   97,   99,   77,  101,   61,

       61,  100,  102,   99,   73,   73,   73,   78,   79,   81,
       80,   80,   80,   99,   82,   99,   95,   99,   59,   59,
       99,   73,  110,   99,  148,   83,  149,   91,   91,   91,
       74,  119,   96,   63,  120,  109,   68,   69,   99,  131,
       86,   70,  103,   71,   83,   92,   84,   84,   85,  106,
      107,   93,   99,  142,   99,   99,  108,   99,   99,   86,
      114,   99,   86,   99,   87,  111,   99,  104,   94,  115,
       88,   89,  112,   99,  121,  124,   93,  116,  113,  117,
      130,   86,  122,   99,   99,   99,  138,   90,  118,  123,
       66,  125,   99,   65,  140,   88,  126,  127,   89,  153,

      134,  132,  135,  133,  167,   67,  128,   99,  173,  129,
       62,   62,   62,  143,  143,   99,  165,  154,  154,  163,
      255,  163,  166,  171,  164,  164,  164,  168,  184,  172,
       83,  174,   85,   85,   85,   76,  177,  144,  145,   68,
       69,  155,  156,  175,   70,   86,   71,  166,   99,   99,
      150,   68,   69,  166,  172,   99,  136,  216,   71,   80,
       80,   80,  146,   99,  183,  145,  157,   86,  176,  156,
      165,   99,  159,  160,   80,   80,   80,  160,  166,  185,
      181,   83,   99,   84,   84,   85,  172,  159,  160,  164,
      164,  164,  160,   99,  159,  160,   86,   99,   99,  182,

      160,   87,   83,  171,   91,   91,   91,   88,   99,  159,
      160,  172,  187,  186,  188,  160,   99,   86,   86,  190,
       99,   99,   92,   99,   90,  189,   99,   99,   93,   99,
       99,  134,   88,  134,   99,  153,   99,   99,   99,   86,
      191,  197,   99,  192,  193,   94,  194,  196,  198,  195,
      199,   99,  200,   93,  203,   99,   99,   99,   99,  206,
       99,  204,  201,  202,  134,   99,  135,  166,  208,  142,
      214,   76,  210,  138,  207,  209,  153,  212,  205,  213,
      211,  140,  217,  217,   99,  227,  227,  215,  231,   99,
      231,  169,  166,  232,  232,  232,  164,  164,  164,  172,

       99,  245,   99,  242,  246,  390,  247,   99,   99,   65,
      233,  236,   76,   99,  233,   68,   69,  237,   99,   99,
      136,   99,   71,  249,  172,  248,  250,  252,  253,   99,
       99,   99,  233,  254,  238,   99,   99,  233,  256,   99,
      251,   99,  237,  258,   99,  259,  257,   99,   99,   99,
       99,  261,   99,  260,  262,   99,   99,   99,   99,  263,
      268,   99,   99,   99,   99,   99,  267,  276,  403,  264,
      272,  265,  275,   99,  266,  273,  274,  269,  142,  270,
      153,  291,  271,  232,  232,  232,  295,  277,   99,  287,
      287,  279,  279,  293,  232,  232,  232,  294,   99,  294,

      299,   99,  302,   99,   99,  292,   99,   99,  160,  296,
      307,  304,  160,   99,  293,   99,   76,  305,   65,  142,
       99,  303,  294,  324,  294,   99,   99,  306,  292,   99,
      160,   99,  281,  281,  281,  160,  312,  308,   99,  309,
       99,  281,  281,  281,  281,  281,  281,  311,  310,   99,
       99,  313,   99,   99,   99,  320,   99,  314,  317,   65,
       99,  316,  321,  281,  281,  281,  281,  281,  281,  153,
      318,  315,  319,  292,   99,  325,   99,   99,  289,  289,
      289,  322,  142,  294,  326,   99,   99,  289,  289,  289,
      289,  289,  289,  323,   99,  338,  292,  338,  348,  347,

      339,  339,  339,   99,   99,   76,   99,   99,  294,  289,
      289,  289,  289,  289,  289,  343,   99,   99,  350,  349,
       99,  344,   65,  352,  351,  353,   99,  354,   99,   99,
       99,   99,  355,   99,   99,  357,  359,   99,  358,   99,
       99,   99,  356,  142,  376,  361,   99,  362,  339,  339,
      339,   99,  364,  363,  360,  339,  339,  339,  375,   99,
       99,   99,  379,  380,   99,   99,   99,  378,   99,  373,
      384,  383,   99,  373,  382,  153,  385,  393,  394,   99,
       99,  381,   99,   65,  397,   99,  386,   99,   99,   99,
      398,  373,   99,   99,  407,   99,  373,   99,  416,  401,

       99,  402,   99,  408,  396,  423,  399,   99,  417,  419,
      400,   76,   99,  411,  410,  411,   99,  412,   99,  420,
      411,  421,  411,  418,  412,   99,  424,  422,   99,  370,
      390,  387,   99,   99,   99,  412,   99,   99,   99,   99,
       99,   99,  412,   99,   99,   99,  335,  370,  332,   99,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   64,  368,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   75,   75,  365,   75,   75,   75,   75,
       75,   75,   75,   75,   98,   98,   99,   99,   98,   98,

      137,  137,  137,   99,  137,  137,  137,  137,  137,  137,
      137,  141,   99,  141,  141,  141,  141,  141,   99,  141,
      141,  141,   64,   64,   99,   99,   64,  340,  340,   64,
      335,   64,   75,   75,  333,  332,   75,  330,  327,   75,
       99,   75,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  170,  170,  170,  178,  178,  179,  179,
      218,  218,  219,  219,  220,  220,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  228,  228,  229,
      229,  230,  230,  235,  235,  240,  240,  241,  241,  243,
      243,  244,  244,  280,  280,  282,  282,  288,  288,  290,

      290,  297,  297,  298,  298,  300,  300,  301,  301,  328,
      328,  329,  329,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  336,  336,  337,  337,  341,
      341,  342,  342,  345,  345,  346,  346,  366,  366,  367,
      367,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  371,  371,  372,  372,  374,  374,   98,   98,
      377,  377,  388,  388,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  391,  391,  392,  392,  395,
      395,  404,  404,  405,  405,  406,  406,  409,  409,  413,

      413,  414,  414,  415,  415,  346,  346,   99,   99,   99,
       99,   99,   99,   99,  286,  225,  285,  284,  283,  278,
      216,   99,   99,   73,  239,  239,  234,  234,  162,   74,
      226,  225,  223,  222,  221,  138,  138,   99,  180,   65,
       99,   73,   73,  169,  162,  158,  152,  151,  150,  147,
      139,  138,   63,  105,   99,   63,   74,   73,   76,   65,
       63,  425,   56,    7,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425
    } ;

static yyconst flex_int16_t yy_chk[1142] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    9,    9,    9,   10,   10,   10,   13,   14,   15,
       13,   14,   14,   19,   30,   30,  418,   21,   34,    5,

        6,   33,   35,   39,   19,   15,   21,   21,   22,   23,
       22,   22,   22,   38,   23,   33,   28,   43,    3,    4,
      402,   23,   39,   50,   69,   25,   69,   25,   25,   25,
       28,   43,   28,   28,   43,   38,   13,   13,   34,   50,
       25,   13,   35,   13,   24,   25,   24,   24,   24,   37,
       37,   25,   41,   64,   49,  401,   37,   44,   46,   24,
       41,   40,   25,   42,   24,   40,   37,   35,   25,   41,
       24,   24,   40,   45,   44,   46,   25,   42,   40,   42,
       49,   24,   45,   47,   51,   48,   59,   24,   42,   45,
       66,   47,   52,   64,   59,   24,   48,   48,   24,   75,

       56,   51,   56,   52,   88,   56,   48,  109,   93,   48,
       62,   62,   62,   65,   65,  190,   87,   76,   76,   86,
      190,   86,   87,   92,   86,   86,   86,   88,  109,   92,
       85,   93,   85,   85,   85,   75,  100,   65,   65,   66,
       66,   76,   76,   99,   66,   85,   66,   87,  100,  108,
      136,   56,   56,   90,   92,  400,   56,  136,   56,   80,
       80,   80,   65,  106,  108,   65,   76,   85,   99,   76,
       90,  110,   80,   80,   83,   83,   83,   80,   90,  110,
      106,   84,  107,   84,   84,   84,   94,   83,   83,  163,
      163,  163,   83,  111,   80,   80,   84,  115,  113,  107,

       80,   84,   91,   94,   91,   91,   91,   84,  112,   83,
       83,   94,  112,  111,  113,   83,  114,   91,   84,  115,
      116,  117,   91,  118,   84,  114,  121,  123,   91,  119,
      120,  134,   84,  134,  124,  287,  399,  126,  398,   91,
      116,  123,  125,  117,  118,   91,  119,  121,  123,  120,
      124,  127,  125,   91,  126,  128,  129,  130,  133,  128,
      131,  127,  125,  125,  135,  132,  135,  165,  129,  143,
      133,  287,  131,  138,  128,  130,  154,  132,  127,  132,
      131,  138,  143,  143,  181,  154,  154,  134,  159,  182,
      159,  170,  165,  159,  159,  159,  164,  164,  164,  171,

      396,  181,  183,  177,  182,  389,  183,  188,  184,  143,
      164,  170,  154,  177,  164,  135,  135,  170,  186,  185,
      135,  187,  135,  185,  171,  184,  186,  188,  188,  189,
      191,  192,  164,  189,  170,  193,  196,  164,  191,  197,
      187,  194,  170,  193,  199,  194,  192,  200,  201,  202,
      204,  197,  205,  196,  199,  203,  206,  207,  210,  200,
      205,  208,  209,  213,  211,  212,  204,  213,  387,  201,
      209,  202,  212,  214,  203,  210,  211,  206,  217,  207,
      227,  235,  208,  231,  231,  231,  237,  214,  245,  227,
      227,  217,  217,  236,  232,  232,  232,  238,  253,  236,

      242,  247,  245,  246,  249,  235,  252,  242,  232,  237,
      253,  247,  232,  274,  238,  254,  227,  249,  217,  219,
      261,  246,  238,  274,  236,  255,  259,  252,  235,  258,
      232,  263,  219,  219,  219,  232,  261,  254,  264,  255,
      266,  219,  219,  219,  219,  219,  219,  259,  258,  270,
      267,  263,  265,  268,  276,  270,  271,  264,  267,  219,
      269,  266,  271,  219,  219,  219,  219,  219,  219,  229,
      268,  265,  269,  291,  272,  276,  277,  273,  229,  229,
      229,  272,  279,  293,  277,  303,  304,  229,  229,  229,
      229,  229,  229,  273,  384,  292,  291,  292,  304,  303,

      292,  292,  292,  307,  308,  229,  313,  310,  293,  229,
      229,  229,  229,  229,  229,  299,  309,  312,  308,  307,
      314,  299,  279,  310,  309,  312,  315,  313,  317,  318,
      319,  299,  314,  320,  321,  317,  319,  324,  318,  322,
      325,  349,  315,  367,  344,  321,  348,  322,  338,  338,
      338,  344,  325,  324,  320,  339,  339,  339,  343,  347,
      350,  362,  348,  349,  343,  355,  354,  347,  363,  339,
      362,  355,  364,  339,  354,  372,  363,  375,  376,  378,
      379,  350,  380,  367,  379,  375,  364,  382,  376,  383,
      380,  339,  385,  386,  393,  397,  339,  410,  407,  385,

      381,  386,  393,  394,  378,  421,  382,  394,  408,  416,
      383,  372,  407,  403,  397,  403,  416,  403,  408,  417,
      411,  419,  411,  410,  411,  419,  422,  420,  421,  369,
      368,  365,  361,  360,  359,  403,  420,  417,  358,  357,
      356,  353,  411,  352,  351,  346,  334,  333,  331,  422,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  428,  330,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  429,  429,  327,  429,  429,  429,  429,
      429,  429,  429,  429,  430,  430,  326,  323,  430,  430,

      431,  431,  431,  316,  431,  431,  431,  431,  431,  431,
      431,  432,  311,  432,  432,  432,  432,  432,  306,  432,
      432,  432,  433,  433,  305,  302,  433,  296,  295,  433,
      286,  433,  434,  434,  285,  284,  434,  283,  278,  434,
      275,  434,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  436,  436,  436,  437,  437,  438,  438,
      439,  439,  440,  440,  441,  441,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  443,  443,  444,
      444,  445,  445,  446,  446,  447,  447,  448,  448,  449,
      449,  450,  450,  451,  451,  452,  452,  453,  453,  454,

      454,  455,  455,  456,  456,  457,  457,  458,  458,  459,
      459,  460,  460,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  463,  463,  464,  464,  465,
      465,  466,  466,  467,  467,  468,  468,  469,  469,  470,
      470,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  472,  472,  473,  473,  474,  474,  475,  475,
      476,  476,  477,  477,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  479,  479,  480,  480,  481,
      481,  482,  482,  483,  483,  484,  484,  485,  485,  486,

      486,  487,  487,  488,  488,  489,  489,  262,  260,  257,
      256,  251,  250,  248,  226,  224,  223,  222,  221,  216,
      215,  198,  195,  180,  174,  173,  168,  167,  161,  152,
      151,  150,  149,  148,  147,  140,  137,  122,  105,  101,
       98,   97,   96,   89,   82,   79,   72,   71,   70,   68,
       58,   57,   54,   36,   32,   29,   26,   18,   16,   12,
       11,    7,    2,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[73] =
    {   0,
0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cref.l"
/*Lembrando que %x indica que somente o estado será executado*/
/*Define dois estados, onde o primeiro liga com comentário e o segundo com arquivos.*/


/* Alguns padrões complexos*/
/* A ideia é realizar a criação de um pequeno subpadrão para facilitar
 * a manipulação futura.*/
/* Universal Character Name: Note que cada padrão fica entre parenteses*/
/*Expoente de float*/
/*Lembrando que + e ? procura qualquer elemento a esquerda do indicado*/
/* Tamanho do inteiro*/
/*Tabela de símbolos*/
#line 22 "cref.l"
	/*Lista contendo um nó e o nome*/
	struct symbol
	{
		struct ref * reflist;
		char * name;
	};

	struct ref
	{
		struct ref * next;
		char * filename;	//Armazena o nome do arquivo
		int flags;	//Utilizado para marcar se é uma definição ou não
		int lineno;	//Linha onde foi encontrado 
	};

	/*Tabela de símbolos simples de tamanho fixo*/
	#define NHASH 9997
	struct symbol symtab[NHASH];

	struct symbol * lookup(char *);
	void addref(int, char *, char *, int);

	char * curfilename;	/*Nome do arquivo atual*/

	int defining;	//Esta nova variável será utilizada para indicar se é uma definição ou não

	/*Pilha de arquivos incluidos*/
	struct bufstack
	{
		struct bufstack * prev; /*Entrada anterior*/
		YY_BUFFER_STATE bs;	/*Buffer salvo*/
		int lineno;	/*Salva o número da linha neste arquivo*/
		char * filename;
		FILE * f;
	} * curbs;

	int newfile(char * fn);
	int popfile(void);

#line 941 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define IFILE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 62 "cref.l"


#line 1136 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 426 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1064 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 64 "cref.l"

	YY_BREAK

case 2:
YY_RULE_SETUP
#line 66 "cref.l"

	YY_BREAK

case 3:
YY_RULE_SETUP
#line 68 "cref.l"

	YY_BREAK

case 4:
YY_RULE_SETUP
#line 70 "cref.l"

	YY_BREAK

case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 72 "cref.l"

	YY_BREAK
/* Comentário C++, uma extesão comum */
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 74 "cref.l"

	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 76 "cref.l"
{
		printf("%s:%d: Unterminated comment\n", curfilename, yylineno);
		return 0;
	}
	YY_BREAK
/*Declaração de palavras chaves. Repare que foi feita uma divisão entre
  * palavras chaves que introduzem uma definição das demais */
case 7:
#line 84 "cref.l"
case 8:
#line 85 "cref.l"
case 9:
#line 86 "cref.l"
case 10:
#line 87 "cref.l"
case 11:
#line 88 "cref.l"
case 12:
#line 89 "cref.l"
case 13:
#line 90 "cref.l"
case 14:
#line 91 "cref.l"
case 15:
#line 92 "cref.l"
case 16:
#line 93 "cref.l"
case 17:
#line 94 "cref.l"
case 18:
#line 95 "cref.l"
case 19:
#line 96 "cref.l"
case 20:
#line 97 "cref.l"
case 21:
#line 98 "cref.l"
case 22:
#line 99 "cref.l"
case 23:
#line 100 "cref.l"
case 24:
#line 101 "cref.l"
case 25:
#line 102 "cref.l"
case 26:
#line 103 "cref.l"
case 27:
#line 104 "cref.l"
case 28:
#line 105 "cref.l"
case 29:
#line 106 "cref.l"
case 30:
YY_RULE_SETUP
#line 106 "cref.l"
{ defining = 1;}
	YY_BREAK
/*Keywords*/
case 31:
YY_RULE_SETUP
#line 109 "cref.l"

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 110 "cref.l"

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 111 "cref.l"

	YY_BREAK
case 34:
YY_RULE_SETUP
#line 112 "cref.l"

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 113 "cref.l"

	YY_BREAK
case 36:
YY_RULE_SETUP
#line 114 "cref.l"

	YY_BREAK
case 37:
YY_RULE_SETUP
#line 115 "cref.l"

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 116 "cref.l"

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 117 "cref.l"

	YY_BREAK
case 40:
YY_RULE_SETUP
#line 118 "cref.l"

	YY_BREAK
case 41:
YY_RULE_SETUP
#line 119 "cref.l"

	YY_BREAK
case 42:
YY_RULE_SETUP
#line 120 "cref.l"

	YY_BREAK
case 43:
YY_RULE_SETUP
#line 121 "cref.l"

	YY_BREAK
/*Constantes. Note o uso dos subpadrões aqui*/
/*Inteiros*/
case 44:
YY_RULE_SETUP
#line 125 "cref.l"

	YY_BREAK
case 45:
YY_RULE_SETUP
#line 126 "cref.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 127 "cref.l"

	YY_BREAK
/*Decimal float*/
case 47:
YY_RULE_SETUP
#line 130 "cref.l"

	YY_BREAK
case 48:
YY_RULE_SETUP
#line 131 "cref.l"

	YY_BREAK
/*Hex float*/
case 49:
YY_RULE_SETUP
#line 134 "cref.l"

	YY_BREAK
/* char const */
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 137 "cref.l"

	YY_BREAK
/* string literal */
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 140 "cref.l"

	YY_BREAK
/*Pontuadores*/
case 52:
YY_RULE_SETUP
#line 143 "cref.l"
{defining = 0;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 145 "cref.l"

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 146 "cref.l"

	YY_BREAK
case 55:
YY_RULE_SETUP
#line 147 "cref.l"

	YY_BREAK
case 56:
YY_RULE_SETUP
#line 148 "cref.l"

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 149 "cref.l"

	YY_BREAK
case 58:
YY_RULE_SETUP
#line 150 "cref.l"

	YY_BREAK
case 59:
YY_RULE_SETUP
#line 151 "cref.l"

	YY_BREAK
/*Identificador. Neste ponto é realizado o reconhecimento de variáveis,
  * palavra-chave, dentre outros.*/
case 60:
YY_RULE_SETUP
#line 155 "cref.l"
{
		addref(yylineno, curfilename, yytext, defining);
	}
	YY_BREAK
/*Espaço em branco*/
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 159 "cref.l"

	YY_BREAK
/* Linha de continuação*/
case 62:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 161 "cref.l"

	YY_BREAK
/*Alguns tratamento para pré-processador*/
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 164 "cref.l"

	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 165 "cref.l"

	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 166 "cref.l"

	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 167 "cref.l"

	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 168 "cref.l"

	YY_BREAK
/*Reconhece include*/
case 68:
YY_RULE_SETUP
#line 171 "cref.l"
{
		BEGIN IFILE;
	}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 174 "cref.l"
{
		{
			int c;
			while((c = input()) && c != '\n');
		}
		newfile(strdup(yytext));
		BEGIN INITIAL;
		}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 183 "cref.l"
{
		fprintf(stderr, "%s:%d bad include line\n", curfilename, yylineno);
		BEGIN INITIAL;
	}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 188 "cref.l"
{
		if(!popfile()) yyterminate();
	}
	YY_BREAK
/*Caracter invalido*/
case 71:
YY_RULE_SETUP
#line 193 "cref.l"
{
	printf("%s, %d: Mystery character '%s'\n", curfilename, yylineno, yytext);
  }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 196 "cref.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1588 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 426 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 426 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 425);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 196 "cref.l"



 /* hash um simbolo */
static unsigned symhash(char *sym)
{
  unsigned int hash = 0;
  unsigned c;

  while(c = *sym++) hash = hash*9 ^ c;

  return hash;
}

struct symbol * lookup(char* sym)
{
  struct symbol *sp = &symtab[symhash(sym)%NHASH];
  int scount = NHASH;		/* how many have we looked at */

  while(--scount >= 0) {
    if(sp->name && !strcmp(sp->name, sym)) { return sp; }

    if(!sp->name) {		/* new entry */
      sp->name = strdup(sym);
      sp->reflist = 0;
      return sp;
    }

    if(++sp >= symtab+NHASH) sp = symtab; /* try the next entry */
  }
  fputs("symbol table overflow\n", stderr);
  abort(); /* tried them all, table is full */

}

void addref(int lineno, char *filename, char *word, int flags)
{
  struct ref *r;
  struct symbol *sp = lookup(word);

  /* don't do dups */
  if(sp->reflist &&
     sp->reflist->lineno == lineno && sp->reflist->filename == filename) return;

  r = malloc(sizeof(struct ref));
  if(!r) {fputs("out of space\n", stderr); abort(); }
  r->next = sp->reflist;
  r->filename = filename;
  r->lineno = lineno;
  r->flags = flags;
  sp->reflist = r;
}

/* print the references
 * sort the table alphabetically
 * then flip each entry's reflist to get it into forward order
 * and print it out 
 */

/* aux function for sorting */
static int symcompare(const void *xa, const void *xb)
{
  const struct symbol *a = xa;
  const struct symbol *b = xb;

  if(!a->name) {
    if(!b->name) return 0;	/* both empty */
    return 1;			/* put empties at the end */
  }
  if(!b->name) return -1;
  return strcmp(a->name, b->name);
}

void printrefs()
{
	struct symbol *sp;

	qsort(symtab, NHASH, sizeof(struct symbol), symcompare); /* Organiza a tabela de simbolo */

	for(sp = symtab; sp->name && sp < symtab+NHASH; sp++)
	{
		char *prevfn = NULL; /* Ultimo arquivo*/

		/* reverse the list of references */
		struct ref *rp = sp->reflist;
		struct ref *rpp = 0;	/* previous ref */
		struct ref *rpn;	/* next ref */

		do
		{
			rpn = rp->next;
			rp->next = rpp;
			rpp = rp;
			rp = rpn;
		} while(rp);

		/* Imprime as palavras e referências */
		printf(" %10s", sp->name);
		for(rp = rpp; rp; rp = rp->next)
		{
			if(rp->filename == prevfn)
			{
				printf(" %d", rp->lineno);
			} else
			{
				printf(" %s:%d", rp->filename, rp->lineno);
				prevfn = rp->filename;
			}
			if(rp->flags & 01) printf("*");
		}
		printf("\n");
	}
}

int main(int argc, char **argv)
{
	int i = 0;

	if(argc < 2)
	{
		fprintf(stderr, "need filename\n");
		return 1;
	}
  for(i = 1; i < argc; i++) {
    if(newfile(argv[i])) yylex();
  }

  printrefs();
  return 0;
}

/* nested input files */
int newfile(char *fn)
{
  FILE *f = fopen(fn, "r");
  struct bufstack *bs;

  /* check if no file */
  if(!f) {
    perror(fn);
    return 0;
  }

  bs = malloc(sizeof(struct bufstack));
  if(!bs) { perror("malloc"); exit(1); }

  /* remember state */
  if(curbs) curbs->lineno = yylineno;

  bs->prev = curbs;
  bs->f = f;
  bs->filename = fn;

  /* set up current entry */
  bs->bs = yy_create_buffer(f,YY_BUF_SIZE);
  yy_switch_to_buffer(bs->bs);
  curbs = bs;
  yylineno = 1;
  curfilename = fn;
  return 1;
}

int popfile(void)
{
  struct bufstack *bs = curbs;
  struct bufstack *prevbs;

  if(!bs) return 0;

  /* get rid of current entry
  fclose(bs->f);
  yy_delete_buffer(bs->bs);

  /* switch back to previous */
  prevbs = bs->prev;
  free(bs);

  if(!prevbs) return 0;

  yy_switch_to_buffer(prevbs->bs);
  curbs = prevbs;
  yylineno = curbs->lineno;
  curfilename = curbs->filename;
  return 1; 
}

